### ISSUE TITLE
handlebars style render fail

### ISSUE THREAD

**Issue by cboseak** [butterflyfx/web#2]
It's showing {{error }} instead of the value that its supposed to render

![image](https://user-images.githubusercontent.com/9941734/27744780-84e71d54-5d86-11e7-9b72-841ca520b89d.png)

**Comment by AkeemMcLennon** [comment]
Hmm, that's strange. I'm not seeing this on my end, but I see where that appears in the template.

Does this happen immediately after you first visit the page, or after form submission? What browser does this occur on?

**Comment by AkeemMcLennon** [comment]
Thanks for letting me know! It looks like the pricing section was linking to an old page.

This should now be fixed.
